changelog.txt, src/qmapshack/gis/trk/filter/filter.cpp
Fixes Issue #5 
Reordering seems not to work on OS X. Fixed it by splitting the track
into two parts and combining these parts in reverse order.
=> [QMS-5] App crashes on using the "Change Start Point" filter

changelog.txt, src/qmapshack/CMakeLists.txt, src/qmaptool/CMakeLists.txt, src/qmt_map2jnx/CMakeLists.txt, src/qmt_rgb2pct/CMakeLists.txt
Use PROJECT_VERSION_* for QMapShack and all other tools
What is the linked issue for this pull request (start with a `#`): #12 
Describe roughly what you have done:
Instead of defining the version number for each sub-project the PROJECT_VERSION_* defines are used for all sub-projects. As a result each application (QMapShack, QMapTool, qmt_map2jnx, qmt_rgb2pct) report the same version number.
What steps have to be done to perform a simple smoke test:
Open `About` menu or use the `--version` command line parameter
Does the code comply to the coding rules and naming conventions [Coding Guidleines](https://github.com/Maproom/qmapshack/wiki/DeveloperCodingGuideline):
Is every user facing string in a tr() macro?
Is the change user facing?
If there are user facing changes did you add the ticket …
=> [QMS-12] Unify versions of all QMapShack tools

.gitignore, changelog.txt, src/qmapshack/device/CDeviceGarmin.cpp, src/qmapshack/device/CDeviceGarmin.h, src/qmapshack/device/IDevice.cpp, src/qmapshack/gis/tcx/CTcxProject.cpp, src/qmapshack/gis/tcx/CTcxProject.h
**What is the linked issue for this pull request (start with a `#`):** #13 
* Add trimmed() to all text readout as there can be leading and trailing spaces
* Decode section `FitnessCourses` and store path as TCX target path
* Read projects from TCX target path
* Detect Edge 5xx and save data as TCX
* Fix testForExternalProject() by mounting the device
* Attach a device or a USB stick with the correct GarminDevice.xml 
* TCX files on the device should be listed
* Send a project to the device -> should be listed
* Restart QMS -> project is listed on the device
* Send project again -> project on the device is replaced.
Does the code comply to the coding rules and naming conventions [Coding …
=> [QMS-13] Add support for Garmin Edge 500

changelog.txt, src/qmapshack/CMainWindow.cpp, src/qmapshack/canvas/CCanvas.cpp, src/qmapshack/gis/db/CSetupDatabase.cpp
Replaced all links with links into the GitHub Wiki
**What is the linked issue for this pull request (start with a `#`):** QMS-#31
Simply replaced all links to Bitbucket pages via search and replace.
* Tested links in the `About` menu
* Tested links in the first start page
=> [QMS-31] Replace links into Bitbucket Wiki

changelog.txt, msvc_64/QMapShack_Installer.nsi
The links for the 2 start menu entries
- Help
- qmapshack.org
now point to the new location at github
**What is the linked issue for this pull request (start with a `#`):** #20
Link targets in the Windows start menu which previously pointing to 
bitbucket now point to the respective github locations.
1. Create a Windows Installer created with the updated QMapShack_Installer.nsi
2. Run the Windows installer
3. Verify that the QMapstack start menu entries "Help" and "qmapshack.org" now direct to pages on github 
**Is every user facing …
=> [QMS-20] Windows Start Menu - link to github

changelog.txt, src/qmapshack/gis/fit/decoder/CFitMessage.cpp, src/qmapshack/gis/fit/defs/fit_const.h
**What is the linked issue for this pull request (start with a `#`):** #8
Couldn't really determine the root cause. However the fields
`eRecordEnhancedSpeed` and `eRecordEnhancedAltitude`
seemed to be decoded twice in each trackpoint record. Can't tell if
this is a bug in QMS or the device. Anyway, if the code ignores the
second set everything seems to be fine.
The example file from the ticket loads well.
[2019-09-06 18-00-09.fit.gz](https://github.com/Maproom/qmapshack/files/3672794/2019-09-06.18-00-09.fit.gz)
**Is every user …
=> [QMS-8] Incorrect elevation for fit files from GPSMAP 66s

changelog.txt, src/qmapshack/locale/qmapshack.ts, src/qmapshack/locale/qmapshack_ca.ts, src/qmapshack/locale/qmapshack_cs.ts, src/qmapshack/locale/qmapshack_de.ts, src/qmapshack/locale/qmapshack_es.ts, src/qmapshack/locale/qmapshack_fr.ts, src/qmapshack/locale/qmapshack_it.ts, src/qmapshack/locale/qmapshack_nl.ts
**What is the linked issue for this pull request (start with a `#`):** #27
I fixed the translation errors in the german file. Should I add the translations from geocaching.com for all languages? (I did it for catalan and after that I questioned wether this is the place to do it :laughing: )
1. Load geocaches into workspace with german language settings
2. Query for "nicht negierte attribute enthält +10" and there should be no more false positives.
**If …
=> [Qms-27] Error in workspace search for attribues

changelog.txt, src/qmapshack/gis/trk/CKnownExtension.cpp, src/qmapshack/gis/trk/filter/filter.cpp
**What is the linked issue for this pull request (start with a `#`):** QMS #19
The `ql` namespace was prepended by `::` causing the files to fail
on some other applications. Removed all occurences of `::ql`
1. Use the `Calculate Terrain Slope` filter on a track
2. Save track as GPX.
3. Test on Oruxmap
=> [QMS-19] Invalid GPX due to `::` in `ql` namespace

changelog.txt, src/qmapshack/map/CMapVRT.cpp, src/qmapshack/map/CMapVRT.h
**What is the linked issue for this pull request (start with a `#`):** QMS #6
Search submaps of a VRT. If all contain overviews set the overview
flag. If one of them does not contain overviews the complete map is
assumed to have no overviews.
* Open a VRT map with more than one submap. Each submap must contain overviews. 
* The debug output should read `has overviews true`
* The map should be displayed over all zoom levels.
**If there are user facing …
=> [QMS-6] Enhance overview detection for VRT maps

changelog.txt, src/qmapshack/mouse/line/IScrOptEditLine.ui
Use the keys O, V, A and T without any control key to switch between
routing modes.
**What is the linked issue for this pull request (start with a `#`):** QMS #14
Simply changed key bindings and tool tips.
Start editing a track. Using the keys O, V, A and T should visibly switch the tool buttons.
=> [QMS-14] Drawing track: Change key bindings

changelog.txt, src/qmapshack/CMakeLists.txt, src/qmapshack/units/CUnitAviation.cpp, src/qmapshack/units/CUnitAviation.h, src/qmapshack/units/CUnitsSetup.cpp, src/qmapshack/units/IUnit.cpp, src/qmapshack/units/IUnit.h, src/qmapshack/units/IUnitsSetup.ui
**What is the linked issue for this pull request (start with a `#`):** #22 
* added CUnitAviation.cpp and CUnitAviation.h to src/qmapshack/units
* modfied other files in src/qmapshack/units to use CUnitAviation.cpp and CUnitAviation.h
Open "unit settings" where a fourth item "Aviation (nm / feet)" appears.
- what's this?
=> [QMS-22] Nautical miles for distances and feet for altitude

changelog.txt, src/qmapshack/device/CDeviceGarminArchive.cpp, src/qmapshack/device/CDeviceGarminArchive.h
Simply remove all child items on deflating the `Archive` folder.
**What is the linked issue for this pull request (start with a `#`):** QMS-#53
I added a signal handler for `itemCollapsed` signal in `CDeviceGarminArchive`. The handler removes all child items.
* Connect a Garmin with an archive folder
* Expand the archive folder -> all items loaded and visible on the map
* Collapse the archive folder -> all items removed on the map
**If there are user …
=> [QMS-53] Unload Garmin `Archive` when folder is deflated

changelog.txt, src/qmapshack/gis/trk/CGisItemTrk.cpp
Don't show CInvalidTrk if track is on a device because the user's
decision can't be stored for the track on the device.
**What is the linked issue for this pull request (start with a `#`):** QMS-#54
Simply added `isOnDevice()` check to the condition showing `CInvalidTrk` dialog.
* Store a track with invalid data on the device.
* When loading the device's data no dialog about invalid points should pop-up.
**If there are user facing changes did you add the …
=> [QMS-54] Disable invalid points dialog for devices

changelog.txt, msvc_64/QMapShack_Installer.nsi, msvc_64/cmake/FindPROJ4.cmake, msvc_64/copyfiles.bat
**What is the linked issue for this pull request (start with a `#`):** QMS-#58
I added proj_6_2 to the find_library section of msvc_64/FindPROJ4.cmake.
I replaced proj_6_1.dll with proj_6_2.dll in both msvc_64/copyfiles.bat  and msvc_64/QMapShack_Installer.nsi.
1. Build QMapShack for Windows, dependeing on teh PROJ library in version 6.2
2. There shall be no dependency errors related to PROJ reported by CMake
3. Neither the copyfiles.bat nor the NSIS installer shall report errors related to the version/filename pf the proj DLL
**Is …
=> [QMS-58] Windows Build and Installer: use PROJ 6.2

changelog.txt, src/qmapshack/dem/CDemPropSetup.cpp, src/qmapshack/dem/CDemPropSetup.h, src/qmapshack/dem/CDemVRT.cpp, src/qmapshack/dem/IDem.cpp, src/qmapshack/dem/IDem.h, src/qmapshack/dem/IDemPropSetup.ui
**What is the linked issue for this pull request (start with a `#`):** QMS-#49
Added "elevation limit" to DEM to highlight elevation above the limit.
Added a Checkbox "Elevation Limit" to the DEM
dialog to toggle visualization of the limit.
Added a Spinbox to the DEM dialog to set the
elevation limit.
If enabled, terrain above the limit will be
colored in magenta.
This feature is useful for VFR flight planning to
check if the planned route is above the terrain.
1. Go to DEM settings
2. Enable the checkbox "elevation limit"
3. adjust the elevation limit to your needs. You can adjust the elevation limit by using the mouse wheel in the spinbox. The elevation limit is to be given in the …
=> [QMS-49] Add "elevation limit" to DEM to

changelog.txt, src/qmapshack/dem/CDemPropSetup.cpp, src/qmapshack/dem/IDemPropSetup.ui, src/qmapshack/gis/CGisWorkspace.cpp, src/qmapshack/gis/trk/CGisItemTrk.cpp, src/qmapshack/gis/trk/CKnownExtension.cpp, src/qmapshack/gis/trk/filter/CFilterDouglasPeuker.cpp, src/qmapshack/gis/trk/filter/CFilterLoopsCut.cpp, src/qmapshack/gis/trk/filter/CFilterOffsetElevation.cpp, src/qmapshack/gis/trk/filter/CFilterSpeedConst.cpp, src/qmapshack/gis/trk/filter/CFilterZeroSpeedDriftCleaner.cpp, src/qmapshack/gis/trk/filter/filter.cpp, src/qmapshack/gis/wpt/CDetailsWpt.cpp, src/qmapshack/helpers/CElevationDialog.cpp, src/qmapshack/plot/CPlotProfile.cpp, src/qmapshack/units/CUnitAviation.cpp, src/qmapshack/units/CUnitAviation.h, src/qmapshack/units/CUnitImperial.cpp, src/qmapshack/units/CUnitImperial.h, src/qmapshack/units/CUnitMetric.cpp, src/qmapshack/units/CUnitMetric.h, src/qmapshack/units/CUnitNautic.cpp, src/qmapshack/units/CUnitNautic.h, src/qmapshack/units/IUnit.cpp, src/qmapshack/units/IUnit.h
**What is the linked issue for this pull request (start with a `#`):** QMS-#64
* Change factor and unit constants to camelCase naming
* Add factor and unit for elevation
* Move meter2elevation() methods to IUnit
* Fix a few locations where baseFactor and baseUnit where used for
elevation.
Try to find all locations in the GUI where the elevation is used and test if it fit's for different unit settings.
**If there are user facing changes did you add the …
=> [QMS-64] Cleanup code in IUnit and subclasses

changelog.txt, src/qmapshack/CMainWindow.cpp
**What is the linked issue for this pull request (start with a `#`):** QMS-#59
Append the string for the widget title if `VERSION_SUFFIX` is set.
Set `VERSION_SUFFIX` in `CMakeLists.txt`, compile and see if the app title has been appended.
=> [QMS-59] Add VERSION_SUFFIX to main widget title

changelog.txt, src/qmapshack/gis/trk/CTrackData.h, src/qmapshack/gis/trk/filter/CFilterNewDate.cpp
**What is the linked issue for this pull request (start with a `#`):** QMS-#37
Query the current time zone setup and create time zone label and correct
date/time edit accordingly. Each of the 4 modes need special handling. 
* Select one of the modes in View->Setup Time Zone
* Edit a track.
* Go to Filter->Change timestamp of track points->Change Time
* Check if the time zone and the time matches the current settings
The initial time is always the current time (UTC) transformed into the selected time zone.
For automatic mode create a track somewhere outside your time zone and test. …
=> [QMS-37] Inconsistent use of time zones

changelog.txt, src/qmapshack/gis/IGisItem.h, src/qmapshack/gis/trk/CTrackData.h, src/qmapshack/gis/wpt/CDetailsGeoCache.cpp, src/qmapshack/gis/wpt/CGisItemWpt.cpp, src/qmapshack/gis/wpt/CGisItemWpt.h, src/qmapshack/helpers/CSelectCopyAction.cpp, src/qmapshack/helpers/ISelectCopyAction.ui
**What is the linked issue for this pull request (start with a `#`):** QMS-#73
* Finetune dialog layout
* Create getLastLog() and getLogs() in CGisItemWpt::geocache_t
* Enhance getInfo() text for geocache
* Open a pocket query
* Copy first cache into another project
* Copy the same cache into the same project
Enhanced test:
* Get an updated pocket query
* Copy the same cache into the same project
**If there are user facing changes did you add the ticket …
=> [QMS-73] Info of a geocache is not correctly shown in Copy Element Window

changelog.txt, src/qmapshack/mouse/line/CLineOpAddPoint.cpp
**What is the linked issue for this pull request (start with a `#`):** QMS-#83
This is a race condition between events for left and right click when
adding points to a track. If the right click ist handled first `idxFocus` is
set to NOIDX. The following left click event did not check for an invalid
`idxFocus` resulting in an out of bounds array access.
-> Check for `idxFocus == NOIDX` 
Follow the instructions in the ticket.
**If there are user facing …
=> [QMS-83] Application Crash

changelog.txt, src/qmapshack/gis/prj/CDetailsPrj.cpp
**What is the linked issue for this pull request (start with a #):** QMS-#100
Trim project keywords and name
to avoid unique whitespaces for
name and keywords
I used QString QString::trimmed() const to avoid unique whitespaces 
Simple test in GUI
=> [QMS-100] Avoid whitespaces in project name and keywords

changelog.txt, src/qmapshack/CMainWindow.cpp, src/qmapshack/gis/CGisWorkspace.cpp, src/qmapshack/gis/CGisWorkspace.h
**What is the linked issue for this pull request (start with a `#`):** QMS-#89
The progress dialog shown when loading a garmin map operates
the event loop. This causes the workspace widget to proceed with
it's initialization. However at this point the QAction objects in
CMainWidget are not restored from configuration, yet.  Including
the Geo search action.
The fix adds a late initialization to CGisWorkspace. It is called via
timer short after the main widget's ctor loading all maps finished.
* Load a Gamin map
* Enable geo search
* Close QMapShack
* Clear the file cache e.g. on Linux `sync; echo 2 > /proc/sys/vm/drop_caches`
* Start QMapShack.
After loading the map (progress bar) the …
=> [QMS-89] Geo search hidden after restarting QMapShack

changelog.txt, src/qmapshack/gis/wpt/CGisItemWpt.cpp
**What is the linked issue for this pull request (start with a `#`):** QMS-#109
I added a link to getInfo() for geocaches, so you can directly fo to the logging page. I diverged from the original feature request, since for me it desn't really make a large difference wether the "Log Geocache" is right aligned or not, so I decided that the effort was not worth it after a html snipped found online didn't achieve what I wanted.
1. Click on a geocache on the map
2. Click on the logging link
**Is every user facing string in a tr() …
=> [QMS-109] Direct link to geocaching logging page

changelog.txt, src/qmapshack/gis/gpx/serialization.cpp, src/qmapshack/gis/wpt/CGisItemWpt.cpp, src/qmapshack/gis/wpt/CGisItemWpt.h
**What is the linked issue for this pull request (start with a `#`):** QMS-#111
* Added recognition for listing services
* Only display logging link for geocaching.com listings
1. Open geocaches from different listing services
2. Open "speech bubble" for each of those
=> [QMS-111] Geocaching logging page - only 1 server used

changelog.txt, src/qmapshack/gis/search/CProjectFilterItem.cpp, src/qmapshack/gis/search/CSearch.cpp
**What is the linked issue for this pull request (start with a `#`):** QMS-#116
* Fixed the cause of losing the field
* Add missing descriptions
1. Open a project
2. Filter the project
3. The filter field should be there regardless of the rating column being shown or not.
=> [QMS-116] Filter edit field lost

changelog.txt, src/qmapshack/gis/search/ISearchExplanationDialog.ui
**What is the linked issue for this pull request (start with a `#`):** QMS-#118
I enabled user to resize boxes in the window
1. Open help dialog for extended search
=> [QMS-118] Too much whitespace in extended search help window

changelog.txt, src/qmapshack/gis/search/CSearch.cpp, src/qmapshack/gis/search/CSearch.h, src/qmapshack/gis/wpt/CGisItemWpt.cpp, src/qmapshack/helpers/CWptIconManager.cpp, src/qmapshack/helpers/CWptIconManager.h
**What is the linked issue for this pull request (start with a `#`):** QMS-#119
I added the possibility to filter for the status of a geocache and greyed out geocaches that are disabled.
1. Open a file with active, disabled and archived geocaches
2. Filter for "status with archived" or similar
3. See that the icon is grey
=> [QMS-119] Better handling of disabled and archived geocaches

changelog.txt, src/qmapshack/gis/wpt/CGisItemWpt.cpp, src/qmapshack/helpers/CWptIconManager.cpp
**What is the linked issue for this pull request (start with a `#`):** QMS-#
I changed the name prefix.
1. Open an archived or disabled geocache
2. Check if you see the icon
=> [QMS-125] Missing icon for not available geocache

changelog.txt, src/qmapshack/gis/wpt/CGisItemWpt.cpp
**What is the linked issue for this pull request (start with a `#`):** QMS-#126
Added an if clause to fix the error.
1. Search for `status equals available `
2. No waypoints should be shown
=> [QMS-126] Wrong search results of status search

changelog.txt, msvc_64/QMapShack_Installer.nsi, msvc_64/copyfiles.bat, src/qmapshack/CMainWindow.cpp, src/qmapshack/setup/CAppSetupLinux.cpp, src/qmapshack/setup/CAppSetupLinux.h, src/qmapshack/setup/CAppSetupWin.cpp, src/qmapshack/setup/CAppSetupWin.h, src/qmapshack/setup/IAppSetup.h, src/qmaptool/CMainWindow.cpp, src/qmaptool/setup/CAppSetupLinux.cpp, src/qmaptool/setup/CAppSetupLinux.h, src/qmaptool/setup/CAppSetupWin.cpp, src/qmaptool/setup/CAppSetupWin.h, src/qmaptool/setup/IAppSetup.h
Adapt Windows installer for offline help support
**What is the linked issue for this pull request (start with a `#`):** QMS-#122
I adapted the Windows installer scripts;
- add Qt5Help.dll
- add the offline documenation files
1. Create a Windows Installer
2. Press F1 or call for help via the menu
=> [QMS-122] Windows: support for offline help

src/qmapshack/gis/IGisItemRate.ui, src/qmapshack/gis/wpt/CGisItemWpt.cpp, src/qmapshack/locale/qmapshack.ts, src/qmapshack/locale/qmapshack_ca.ts, src/qmapshack/locale/qmapshack_cs.ts, src/qmapshack/locale/qmapshack_de.ts, src/qmapshack/locale/qmapshack_es.ts, src/qmapshack/locale/qmapshack_fr.ts, src/qmapshack/locale/qmapshack_it.ts, src/qmapshack/locale/qmapshack_nl.ts, src/qmapshack/locale/qmapshack_ru.ts
The lintian QA tool reported a spelling error for the Debian package build:
* Seperate -> Separate
=> Fix spelling errors.

changelog.txt, src/qmapshack/gis/rte/IScrOptRte.ui
**What is the linked issue for this pull request (start with a `#`):** QMS-#151
I added the tooltip.
Just hoover the mouse over the button.
=> [QMS-151] Missing tooltip in route toolbar

changelog.txt, src/qmapshack/gis/ovl/CScrOptOvlArea.cpp, src/qmapshack/gis/rte/CScrOptRte.cpp, src/qmapshack/gis/trk/CScrOptTrk.cpp, src/qmapshack/gis/wpt/CScrOptWpt.cpp, src/qmapshack/gis/wpt/CScrOptWptRadius.cpp, src/qmapshack/helpers/CDraw.cpp, src/qmapshack/helpers/CDraw.h, src/qmapshack/mouse/IScrOpt.cpp, src/qmapshack/mouse/IScrOpt.h, src/qmapshack/mouse/line/CScrOptRangeLine.cpp, src/qmapshack/mouse/range/CScrOptRangeTrk.cpp
**What is the linked issue for this pull request (start with a `#`):** QMS-#148
Add method `moveTo()` to `IScrOpt` to unify placement
and to take care of canvas borders.
Click on an item close to the canvas border. It should be visible.
=> [QMS-148] Misplaced track info window

changelog.txt, src/qmapshack/CMakeLists.txt, src/qmapshack/gis/rte/router/CRouterBRouter.cpp, src/qmapshack/gis/rte/router/CRouterBRouter.h, src/qmapshack/gis/rte/router/CRouterMapQuest.h, src/qmapshack/gis/rte/router/CRouterOptimization.cpp, src/qmapshack/gis/rte/router/CRouterOptimization.h, src/qmapshack/gis/rte/router/CRouterRoutino.cpp, src/qmapshack/gis/rte/router/CRouterRoutino.h, src/qmapshack/gis/rte/router/CRouterSetup.cpp, src/qmapshack/gis/rte/router/CRouterSetup.h, src/qmapshack/gis/rte/router/IRouter.h, src/qmapshack/helpers/CProgressDialog.cpp, src/qmapshack/mouse/line/ILineOp.h, src/qmapshack/mouse/line/IMouseEditLine.cpp, src/qmapshack/mouse/line/IMouseEditLine.h, src/qmapshack/mouse/line/IScrOptEditLine.ui
**What is the linked issue for this pull request (start with a `#`):** QMS-#68
Since the TSP somehow fascinated me, I decided to write my own algorithm to optimize routes using the routers already available in QMS.
I adapted the routers, so they also return the cost of the route calculated using `calcRoute`. This enables the algorithm to actually optimize on what the router is trying to minimize.
The only option left to speed up that comes to my mind would be to intercept the `calcRoute` calls for the points the user actually uses, however I didn't find a good possibility to do so.
1. You have to have a router installed that is capable of fast routing.
2. Draw a route
3. Press the …
=> [QMS-68] Route Optimization

changelog.txt, src/qmapshack/canvas/CCanvas.cpp, src/qmapshack/dem/CDemDraw.cpp, src/qmapshack/dem/CDemDraw.h, src/qmapshack/dem/CDemVRT.cpp, src/qmapshack/dem/CDemVRT.h, src/qmapshack/dem/IDem.h
**What is the linked issue for this pull request (start with a `#`):** QMS-#132
Avoid to call GDALDataset::RasterIO() if current scale is out of  valid scale. To achieve that the out of scale information derived during CDemVRT::draw() has to be stored and used in getElevationAt() getSlopeAt().
* Load  DEM
* Set the scale bounds
* Out of the scale bounds no elevation data should be shown in the status bar
**If there are user facing changes did you add the …
=> [QMS-132] Do not load DEM data out of scale

changelog.txt, src/qmapshack/locale/qmapshack_fr.ts
**What is the linked issue for this pull request (start with a `#`):** QMS -#153
I fixed some more french strings, and added a few more.
1   Open QMapShack with LANG=fr_FR.UTF-8 and open a new view.
2  The select trackpoint range tooltip is now translated
no code
no code
The existing changelog entry is good enough I think
=> some more french translation improvements.

changelog.txt, src/qmapshack/device/CDeviceWatcherLinux.cpp
**What is the linked issue for this pull request (start with a `#`):** QMS-#156
I added check in CDeviceWatcherLinux::slotDeviceAdded(), testing if the device is removable. Non-removable devices can't be GPS devices. They are most likely your system drives.
* Start QMapShack with -d option
* You shouldn't see any log about probing system drives anymore.
* Plugin a GPS device
* The device should be listed.
**If there are user facing changes did you add …
=> [QMS-156] Check if device is removable

changelog.txt, src/qmapshack/gis/CGisListWks.cpp, src/qmapshack/gis/CGisWorkspace.cpp, src/qmapshack/gis/CGisWorkspace.h, src/qmapshack/gis/search/CSearch.cpp, src/qmapshack/gis/search/CSearchLineEdit.cpp, src/qmapshack/gis/search/CSearchLineEdit.h
**What is the linked issue for this pull request (start with a `#`):** QMS-#164
* Fixed non-filtering
* Added timout to start filtering
1. Apply a filter
2. Load file with many Items
3. See that filter is applied
4. Change the filter
5. See that you don't hang after typing single characters if you are typing normally
=> [QMS-164] Workspace filter is not applied to newly loaded projects

changelog.txt, src/qmapshack/dem/IDemPropSetup.ui, src/qmapshack/map/IMapPropSetup.ui
**What is the linked issue for this pull request (start with a `#`):** QMS-#173
Replaced tool tips as suggested
Check tool tips for scale slider in the maps and DEM lists.
=> [QMS-173] Misleading help text for DEM range slider

changelog.txt, src/qmapshack/gis/trk/CGisItemTrk.cpp, src/qmapshack/gis/trk/CGisItemTrk.h
Order start and end point of range by their total index.
**What is the linked issue for this pull request (start with a `#`):** QMS-#183
Start and end point where taken as provided. However for a backward selection they must be 
swapped to have the point with the lower index as point 1 and the one with the larger index as point 2.
* Open edit window of track
* Select a range in the track from first point at the right side and second at the left side.
* The range data (on top of graphs, third column) must show positive values. Regardless of the order of selected points. …
=> [QMS-183] Backward range selection causing small issues

changelog.txt, src/qmapshack/dem/CDemVRT.cpp, src/qmapshack/map/CMapVRT.cpp, src/qmaptool/helpers/CGdalFile.cpp, src/qmt_map2jnx/main.cpp
**What is the linked issue for this pull request (start with a `#`):** QMS-#201
I just fixed the code according to GDAL's suggestions in the deprecation warning.
Compile and enjoy the lack of senseless warnings.
=> [QMS-201] Fix GDAL deprecation warnings

changelog.txt, src/qmapshack/map/garmin/CGarminTyp.cpp
**What is the linked issue for this pull request (start with a `#`):** QMS-#204
If the typ file has a bad codec number for UTF8 the code will be
a nullptr. As a consequence the pointer has to be tested before
it is used.
Download and activate the map from the ticket.
=> [QMS-204] Garmin Map: Fix crash because of bad codec number

changelog.txt, src/qmapshack/CMakeLists.txt, src/qmapshack/gis/CGisListWks.cpp, src/qmapshack/gis/CGisWorkspace.cpp, src/qmapshack/gis/db/CDBProject.cpp, src/qmapshack/gis/db/CDBProject.h, src/qmapshack/gis/db/CResolveDatabaseConflict.cpp, src/qmapshack/gis/db/CResolveDatabaseConflict.h, src/qmapshack/gis/db/IResolveDatabaseConflict.ui, src/qmapshack/gis/gpx/CGpxProject.cpp, src/qmapshack/gis/prj/IGisProject.cpp, src/qmapshack/gis/prj/IGisProject.h, src/qmapshack/gis/summary/CGisSummaryDropZone.cpp, src/qmapshack/gis/tcx/CTcxProject.cpp, src/qmapshack/gis/tnv/CTwoNavProject.cpp
**What is the linked issue for this pull request (start with a `#`):** QMS-#172
* Added seperate dialog class for database conflict with checkbox
* catched error of cloning geocaches
1. Copy two different versions of a geocache into two different database folders
2. Save workspace
3. Select that you want to replace the geocache
4. See in the appearing database conflict that you can choose action for all and that if you provoke multiple errors you will not be asked again.
**Is the …
=> [QMS-172] Select action "for all" in Database Conflict

changelog.txt, src/qmapshack/gis/gpx/serialization.cpp
**What is the linked issue for this pull request (start with a `#`):** QMS-#
* Made check for 'available' and 'archived' properties case insensitive
1. Open a file with lower-case availability of geocaches and see that they are correctly displayed
2. Open a file with first letter upper-case availability of geocaches and see that they are correctly displayed
=> [QMS-207] Fixing Availability of Geocaches

changelog.txt, src/qmapshack/gis/rte/router/CRouterRoutino.cpp, src/qmapshack/gis/rte/router/CRouterRoutino.h
**What is the linked issue for this pull request (start with a `#`):** QMS-#158
I have added extra search paths for databasepath/[<prefix>-]profiles.xml and default_ routino_data_path/profiles.xml. Similar to what routino cammandline does.  This is done in the buildDatabaseList method.  This has required moving the parseProfilesXML calls into the calcRoute methods and expanding the userData argument to a map variable containing the database pointer and the path to an existing profiles.xml. 
1. Run routing without any profiles.xml in the database folder. Uses profiles.xml from the default routino path.
2. Create a prefix-profiles.xml in the database folder with slightly different …
=> [QMS-158] Change Routino Profiles search for [prefix-]profiles.xml

changelog.txt, src/qmapshack/gis/rte/router/CRouterRoutino.cpp
**What is the linked issue for this pull request (start with a `#`):** QMS-#217
Routino_GetProfile returns a NULL if a requested profile is not in the profiles xml.  This fix catches the NULL return value as an error and issues a User Message.  
1. Modify a profile name in an existing working profiles.xml file.  Try to use that profile - an error is issued and routing is stops gracefully without aborting.
**If there are user facing changes did you add …
=> [QMS-217] Fix Crash in Profile

changelog.txt, src/qmapshack/gis/rte/router/CRouterOptimization.h, src/qmapshack/gis/rte/router/CRouterRoutino.cpp, src/qmapshack/gis/wpt/CGisItemWpt.cpp, src/qmapshack/helpers/CDraw.cpp, src/qmapshack/map/CMapIMG.cpp, src/qmapshack/mouse/IMouseSelect.cpp, src/qmaptool/helpers/CDraw.cpp, src/qmaptool/overlay/COverlayCutMap.cpp
**What is the linked issue for this pull request (start with a `#`):** QMS-#216
Add `#include <QPainterPath>` whereever `QPainterPath` is used.
Additionally ran code beautifier
Code should compile with QT5.15.
=> [QMS-216] QMapShack does not compile with Qt-5.15

changelog.txt, src/qmapshack/gis/ovl/CGisItemOvlArea.cpp, src/qmapshack/gis/rte/CGisItemRte.cpp, src/qmapshack/gis/search/CSearch.cpp, src/qmapshack/gis/search/CSearch.h, src/qmapshack/gis/trk/CGisItemTrk.cpp, src/qmapshack/gis/wpt/CGisItemWpt.cpp
**What is the linked issue for this pull request (start with a `#`):** QMS-#223
Add new search properties:
* QMS Type (Route, Track, Wpt, Area)
* GC Type (Traditional, Unknown etc.)
* GC Owner
* logged by
* latest log date
* latest log type
* latest log by
1. Conduct a search for these properties
=> [QMS-223] Add additional filter properties

changelog.txt, src/qmapshack/IMainWindow.ui, src/qmapshack/gis/search/CSearchExplanationDialog.cpp, src/qmapshack/gis/trk/IScrOptTrk.ui, src/qmapshack/map/CMapIMG.cpp, src/qmapshack/realtime/CRtSelectSource.cpp, src/qmapshack/realtime/CRtWorkspace.cpp, src/qmapshack/realtime/gpstether/CRtGpsTetherInfo.cpp, src/qmapshack/setup/CLogHandler.cpp, src/qmapshack/units/ITimeZoneSetup.ui, src/qmaptool/setup/CLogHandler.cpp, src/qmaptool/units/ITimeZoneSetup.ui
**What is the linked issue for this pull request (start with a `#`):** QMS-#231
Changed the spelling of some English terms, e.g. fullscreen, realtime, etc.
1. Create new language files
1. See improved spelling of corrected terms
=> QMS-231 Improve English spelling

changelog.txt, src/qmapshack/mouse/CMouseRuler.cpp
Instead of showing courses like `-45°`, we now display `315°`.
This applies to the course displayed next to the line, and to the table.
**What is the linked issue for this pull request (start with a `#`):** QMS-#240
Fixed #240
Add a simple `?` expression in the table update function as in the line drawing function.
1. Open a empty map view with an arbitrary map at an arbitrary position
2. Right click on the map and select 'Ruler' to open the distance ruler tool
3. Draw a rectangle or any other figure with courses > 180 degrees, e.g. north west
4. The courses are now displayed properly :-) …
=> Ruler tool: Don't show negative courses

changelog.txt, src/qmapshack/tool/CMapVrtBuilder.cpp, src/qmapshack/tool/CRoutinoDatabaseBuilder.cpp
At least with Qt 5.15 it happened that QListWidget::findItems
accidentially returned an empty list. The new for-loop fixes that.
**What is the linked issue for this pull request (start with a `#`):** QMS-#244
I changed the for-loop so that it can't miss list items anymore.
1. Go to 'Tool -> Create Routino Database
2. Select a *.pbf file
3. Select a path for your Routino database
4. Select a prefix
5. Press 'Start' button
**Does the code comply to the coding rules and naming conventions [Coding Guidelines](https://github.com/Maproom/qmapshack/wiki/DeveloperCodingGuideline …
=> [QMS-244] Unable to create routino database

changelog.txt, src/qmapshack/canvas/CCanvas.cpp, src/qmapshack/canvas/CCanvas.h, src/qmapshack/plot/IPlot.cpp
Save size before it gets closed.
**What is the linked issue for this pull request (start with a `#`):** QMS-#235
Save the profile window size when the profile gets switched from window mode to on-screen mode.
* Load a track
* Highlight the track to open the profile view
* Switch profile view to window mode
* Change size of profile window
* Toggle back to on-screen mode
* Toggle back to window mode 
-> now the profile window must have the exact same size as before.
**Is the change user …
=> [QMS-235] Save track profile window's geometry when window gets closed

changelog.txt, src/qmapshack/gis/db/IDBMysql.cpp
**What is the linked issue for this pull request (start with a `#`):** QMS-#254
Simply added the option to reconnect to the MySQL connector.
* Connect to a MySQL server with automatic disconnect
* Wait idle time
* Next database interaction should work without error.
=> [QMS-254] MySQL: QMapShack does not automatically reconnect

changelog.txt, src/qmapshack/gis/CGisListDB.cpp
Added the missing update() call.
**What is the linked issue for this pull request (start with a `#`):** QMS-#257
I added the missing update() call.
1. Right-click on the root item of the database tree
2. Click on 'Add Folder'
3. Type in a folder name and select 'Group'.
4. Click 'OK' and the folder gets created.
5. Right-click on that folder.
6. Click on 'Import from Files…'
7. Select a gpx file and import it.
**Is …
=> [QMS-257] Import gpx file to group folder does not trigger update

changelog.txt, src/qmapshack/gis/fit/serialization.cpp
**What is the linked issue for this pull request (start with a `#`):** QMS-#262
The helper function 
```
static QDateTime toDateTime(quint32 timestamp)
```
did not return the UTC timestamp but the local one. Used converting method.
* Load the FIT file from the ticket.
* Copy the track into a gpx project
* Save the gpx project
* Convert the track with gpsbabel
* Compare timestamps in between both GPX
* Load both GPX into QMapShack
* All three tracks (FIT, QMS GPX, gpsbabel GPX) must start with the same timestamp
**Is every user …
=> [QMS-262] Wrong timestamp when loading FIT

CMakeLists.txt, changelog.txt, src/qmapshack/gis/trk/CGisItemTrk.cpp, src/qmapshack/mouse/range/CScrOptRangeTool.cpp
**What is the linked issue for this pull request (start with a `#`):** QMS-#268
The root cause is the track graph as child in the range select
tool. Both are registered visuals of the track. When destroying
the track the range select tool is destroyed first destroying it's
children. This renderes all pointers in the copied list of
registered visuals invalid.
To fix that we have to pick the first element in the list of
registered visuals and destroyi it. This has to be repeated
until the list is empty.
* Load some gpx or fit file
* Right click on one of the tracks and select "Select Range"
* Right click on the associated project and close it.
-> no crash must occur. The mouse cursor must …
=> [QMS-268] Crash after closing project where range is being selected

CMakeLists.txt, changelog.txt, msvc_64/3rdparty.txt, msvc_64/QMapShack_Installer.nsi, msvc_64/cmake/FindPROJ4.cmake, msvc_64/copyfiles.bat
**What is the linked issue for this pull request (start with a `#`):** QMS-#264, QMS-#270, QMS-#273
Update the windows related build scripts as follows
CMakeLists.txt
+ adapt to using Qt5.12.10
FindPROJ4.cmake:
+ add support for proj 6.3
3rdparty.txt:
+ improve references to licenses
copyfiles.bat:
+ adapt to using Qt5.12.10
+ proj 6.3 support
+ improve references to licenses
+ copy LICENSE as 1LICENSE.txt
QMapShack_Installer.nsi: adapt to using Qt5.12.10
+ proj 6.3 support
+ improve references to licenses
+ instead of LICENSE: install 1LICENSE.txt
+ additionally install the help search index files (fts) for QMS and QMT
**What …
=> [QMS-264] Windows: adapt build scripts for 1.15.1 release

changelog.txt, src/qmapshack/gis/rte/router/brouter/CRouterBRouterTilesPage.cpp, src/qmapshack/gis/rte/router/brouter/CRouterBRouterTilesSelect.cpp, src/qmapshack/gis/rte/router/brouter/CRouterBRouterTilesSelectLayout.h
**What is the linked issue for this pull request (start with a `#`):** QMS-#265
Return nullptr in CRouterBRouterTilesSelectLayout::itemAt() and CRouterBRouterTilesSelectLayout::takeAt() if index is out of range.
Go to the tile selection page of the BRouter setup wizard. No crash must occure.
=> [QMS-265] Fix crash in CRouterBRouterTilesSelectLayout

changelog.txt, src/qmapshack/gis/rte/router/CRouterRoutino.cpp
**What is the linked issue for this pull request (start with a `#`):** QMS-#275
In CRouterRoutino.cpp: Add two new lines for Spanish and Czech languages in the combolanguage.
1. Open the Routing Panel- Select Routino offline as routing engine
2. Select your Profile, Mode,and Database. For language Select Spanish.
3. Go to the canvas. Add new route and save it.
4. On the canvas: Click on the new route and check the 'Route instructions' button
5. Click on a point marked in cyan and route instructions should be shown in Spanish
*Remark: First line translation depends on your local language for QMS. Second and third line translations depend on the selected language by the user in the …
=> [QMS-275] Add languages in Routino widget.

changelog.txt, src/qmapshack/mouse/line/IMouseEditLine.cpp
**What is the linked issue for this pull request (start with a `#`):** QMS-#279
Added missing `updateStatus()` call to undo/redo handler.
Create a track as described in the ticket. The track metric should update now when you do an undo/redo
=> [QMS-279] Track metrics not updated when using UNDO / REDO in Edit mode

changelog.txt, src/qmapshack/gis/IGisItem.cpp, src/qmapshack/gis/qms/serialization.cpp
**What is the linked issue for this pull request (start with a `#`):** QMS-#282
* Fixed reported bug by always updating decorations on loading of
database
* Updated comment to better reflect what happens
1. Open saved database project with items that have tags
2. See that those tags now appear
**Did you add the ticket number and title into the changelog? Keep the …
=> [QMS-282] Tags icons/rating disappear from workspace after saving and closing a project

changelog.txt, src/qmapshack/map/CMapDraw.cpp, src/qmapshack/map/CMapItem.cpp, src/qmapshack/map/CMapItem.h
**What is the linked issue for this pull request (start with a `#`):** QMS-#285
For each map a hash is calculated over the 1st 1024 bytes. For some WMTS maps this seems to low. Increased the amount of bytes to 4096
See ticket for test.
=> [QMS-285] WMTS-based maps aren't restored correctly

changelog.txt, src/qmapshack/gis/trk/CEnergyCycling.cpp
**What is the linked issue for this pull request (start with a `#`):** QMS-#299
Simply added the `beginGroup()` and `endGroup()` calls. The section name is `EnergyCycling`
1. Use energy calculator
2. Check config for section `EnergyCycling`
=> [QMS-299] Store config of CEnergyCycling in own section

changelog.txt, src/qmapshack/gis/ovl/CGisItemOvlArea.cpp, src/qmapshack/gis/rte/CGisItemRte.cpp, src/qmapshack/gis/trk/CGisItemTrk.cpp, src/qmapshack/gis/wpt/CGisItemWpt.cpp, src/qmapshack/mouse/CMouseSelect.cpp, src/qmapshack/mouse/IMouseSelect.cpp, src/qmapshack/mouse/IMouseSelect.h
**What is the linked issue for this pull request (start with a `#`):** QMS-#220
Root cause was using the pixel coordinates of the items. This is
quite fast as long as the item is in the visible map. However once
it is outside the visible part these coordinates are invalidated.
Therefore the compare will fail.
Using the real coordinates is a bit more effort especially for
tracks, routes and areas. As the coordinates of these items can be
changed (or points get hidden) at any time the resulting polylline
should be derived on-the-fly. To store a copy would need some
failsafe mechanism to update when needed.
This is a bit slower than before.  Tested with 393 tracks and 2624
waypoints the difference seems to be around factor 1.5. Updating
the GUI takes …
=> [QMS-220]  "Select items from map" misses items

changelog.txt, src/qmapshack/gis/CGisListWks.cpp, src/qmapshack/gis/CGisListWks.h, src/qmapshack/gis/CGisWorkspace.h, src/qmapshack/gis/prj/IGisProject.cpp, src/qmapshack/gis/prj/IGisProject.h, src/qmapshack/gis/qms/serialization.cpp
**What is the linked issue for this pull request (start with a `#`):** QMS-#311
* Add automatic sync. with device option to project item's
workspace menu.
* Add all necessary hooks to trigger a sync. on a new device or
project change
1. Load a project into the workspace
2. Right mouse button context menu in the workspace list
3. select `Autom. sync. w. Device` -> a `S` should appear in the decorations coulmn
4. Attach your device to the PC
5. When the device shows up the project should be synced with the device
6. If you change the project it should be synced with the device …
=> [QMS-311] Automatically save projects to device

changelog.txt, src/qmapshack/canvas/CCanvas.cpp, src/qmapshack/poi/CPoiDraw.cpp, src/qmapshack/poi/CPoiDraw.h, src/qmapshack/poi/CPoiItem.h, src/qmapshack/poi/CPoiPOI.cpp, src/qmapshack/poi/CPoiPOI.h, src/qmapshack/poi/IPoi.h
**What is the linked issue for this pull request (start with a `#`):** QMS-#321
I improved the name selection process. The assumption is made that when there is an `alt_name` that there would be a better 'normal' name, if that is not the case, I can add alt names to the selection process, however there seems to be disagreement on how to add those in OSM (I've seen `alt_name=`, `alt_name1=` and `alt_name_1=`). Also there are `loc_name` `short_name` `official_name` `reg_name`
1. Select POI with different name possibilities to copy to workspace
2. See that your locale is …
=> [QMS-321] Improve name selection for POI

src/qmapshack/CMakeLists.txt, src/qmapshack/gis/CGisWorkspace.cpp, src/qmapshack/gis/CGisWorkspace.h, src/qmapshack/gis/Poi.h, src/qmapshack/gis/wpt/CGisItemWpt.cpp, src/qmapshack/gis/wpt/CGisItemWpt.h, src/qmapshack/helpers/Tristate.h, src/qmapshack/mouse/CMouseNormal.cpp, src/qmapshack/poi/CPoiIconCategory.h, src/qmapshack/poi/CPoiPOI.cpp, src/qmapshack/poi/CPoiPOI_TagMap.cpp, src/qmapshack/poi/CRawPoi.cpp
QMS-#314
I added that the POIs when copied over to a project now get a symbol that match their type, if available.
1. Open a *.poi file
2. Copy POIs over to a project via right-click or 'Select Items On Map'
3. See that you are asked if there is no symbol to choose one.
**Did you add the ticket number and …
=> [QMS-314] Fix/Add POI categories (Resolve POIs to garmin symbols)

src/qmapshack/poi/CPoiDraw.cpp, src/qmapshack/poi/CPoiDraw.h
* Implemented changes introduced in the dev branch to CDrawPoi
QMS-#337
I added the changed signature of `setProjection` to `CDrawPoi`
1. See that it compiles
=> [QMS-337] Upgrade to Proj 8 API

changelog.txt, src/qmapshack/poi/CPoiPOI.cpp, src/qmapshack/poi/CPoiPOI.h
QMS-#307
I added checking for bounding box when fetching POIs.
Loading all categories at once (instead of querying the same area multiple times) would take some effort to do in a sensible way and at least on my machine it works relatively smoothly now as long as it is not zoomed out too far.
1. Activate POI file
2. Move outside bounding box of loaded file
3. See that loading does not take any time (before it did) …
=> [QMS-307] Optimization of POI query

changelog.txt, src/qmapshack/mouse/CMouseSelect.cpp, src/qmapshack/mouse/CMouseSelect.h
QMS-#353
Simply add missing update handler
* Load a couple of data into the workspace.
* Select the data with "Select Items on Map" .
* The on-screen message lists all items selected.
* Now remove the project from the workspace.
-> List of selected items should update. The same should happen if you hide/show the project.
**Did you add the ticket number and title into the changelog? Keep the numeric order in each …
=> [QMS-353] "Select Items on Map" does not update when items are removed

changelog.txt, src/qmapshack/CMainWindow.cpp, src/qmapshack/CMainWindow.h, src/qmapshack/gis/tnv/serialization.cpp, src/qmapshack/helpers/Platform.h, src/qmapshack/map/CMapIMG.cpp, src/qmapshack/map/CMapIMG.h, src/qmapshack/map/CMapJNX.h, src/qmapshack/tool/IToolShell.cpp, src/qmaptool/shell/CShell.cpp, src/qmt_map2jnx/argv.cpp, src/qmt_map2jnx/main.cpp
QMS-#360
Replaced WIN32 define by Q_OS_WIN64
Code should compile in Windows without problems.
=> [QMS-360] Fix compile flags for Windows 64bit

changelog.txt, src/qmapshack/gis/fit/serialization.cpp
QMS-#343
I check if the fit message contains the altitude. If this is the case I will set it. If it is not set, it is invalid due to the constructor for the point.
1. Loading the fit file from the ticket
2. Select hiding invalid point
3. Check the displayed accumulated elevation change.
I did not touch code …
=> [QMS-343] .fit files from Suunto app have many trackpoints with elevation = 0 

changelog.txt, src/qmapshack/gis/fit/decoder/CFitDevFieldDefinitionState.cpp, src/qmapshack/gis/fit/decoder/CFitFieldDataState.cpp, src/qmapshack/gis/fit/decoder/CFitFieldDefinition.cpp, src/qmapshack/gis/fit/decoder/CFitFieldDefinition.h, src/qmapshack/gis/fit/decoder/IFitDecoderState.cpp, src/qmapshack/gis/fit/decoder/IFitDecoderState.h, src/qmapshack/gis/fit/defs/CFitFieldProfile.cpp, src/qmapshack/gis/fit/defs/CFitFieldProfile.h, src/qmapshack/gis/fit/defs/fit_const.h
QMS-#362
More than one active developer data id is supported now.
-  Adding a developer data index field to the
CFitFieldProfile
-  Adding a developer data index field to the
CFitFieldDefinition
-  If a local developer field profile is created
the developer data index is used, not only the
field number
- If a eMesgNumDeveloperDataId (developer_data_id)
mesg arrives only the local developer field
profiles for this ID are deleted
-  A field definition is now always searched by
his field number and its developer data index, see
CFitFieldDataState::handleDevField()
-  A file …
=> [QMS-362] Fit files containing more than one developer data ID cannot be opened. e.g. from a Garmin FR 935 and a connected Stryd footpod

changelog.txt, src/qmapshack/gis/search/CSearch.h
QMS-#363
This is dues to missing default initializers for CSearch::serach_t.
Applied default values.
Repeat the test from the ticket. -> Projects should load with items
=> [QMS-363] GIS items missing in projects loaded from file or database

changelog.txt, src/qmapshack/gis/gpx/serialization.cpp
QMS-#371
Test for empty list in `void CGisItemWpt::readGcExt(const QDomNode& xmlCache)`
Use same files causing the crash. -> no crash
=> [QMS-371] Crash while loading geocache from TwoNav device

changelog.txt, src/qmapshack/plot/IPlot.cpp
QMS-#375
overrideWindowFlags() is a bad idea. Use setWindowFlags()
Perform the steps from the ticket.
=> [QMS-375] On-screen profile window has no close button

changelog.txt, src/qmapshack/CMainWindow.cpp, src/qmapshack/CMainWindow.h
QMS-#380
Switch window state by adding / removing
fullscreen flag from existing set of flags.
Removed old and over complicated code.
Repeat steps from the ticket
=> [QMS-380] Toggle fullscreen does not work

changelog.txt, src/qmaptool/CMakeLists.txt, src/qmaptool/tool/CToolCutMap.cpp, src/qmaptool/tool/CToolGDALGroupBox.cpp, src/qmaptool/tool/CToolGDALGroupBox.h, src/qmaptool/tool/CToolPalettize.cpp, src/qmaptool/tool/CToolRefMap.cpp, src/qmaptool/tool/IToolCutMap.ui, src/qmaptool/tool/IToolGDALGroupBox.ui, src/qmaptool/tool/IToolPalettize.ui, src/qmaptool/tool/IToolRefMap.ui
QMS-#382
* Add CToolGDALGroupBox for the options
* Add options to Cut, Reference and Palettize tool
You would need to use the tools and check the outcome.
=> [QMS-382] QMapTool: Allow customized GDAL parameters

changelog.txt, src/qmapshack/CMakeLists.txt, src/qmapshack/helpers/CTryMutexLocker.h, src/qmapshack/poi/CPoiPOI.cpp, src/qmapshack/poi/CPoiPOI.h
QMS-#389
* Apply the mutex to all public methods of CPoiPOI.
* For all the find and tooltip methods test if the
mutex would block. If it would block leave the
method.
There is no sense in doing find and tooltip
while the draw thread is still gathering information.
Perform the test steps from the ticket
=> [QMS-389] Crash when loading/drawing POIs

changelog.txt, src/qmapshack/gis/IGisItemRate.ui, src/qmapshack/locale/qmapshack_de.ts
QMS-#400
* Set focus order in UI file
* Fix dialog title
* Fix typo in translation
Open tags dialog and start typing.
=> [QMS-400] Set focus in text field

changelog.txt, src/qmapshack/mouse/range/IScrOptRangeTool.ui
Removed a minimum size so that the dialog resizes correctly on larger fonts.
QMS-#414
Removed a minimum size so that the dialog resizes correctly on larger fonts.
1. From the main menu select View->Set Map Font S
2. Select a font with size 14, for example Noto Sans Regular 14.
3. Select a track, select the range tool.
4. Select the last track point.
5. The last track point shall be fully visible.
=> [QMS-414] CScrOptRangeTool: Fix layout for larger fonts.

src/qmapshack/locale/qmapshack_de.ts
QMS-396
Updated the german translation. There is an automatic change for the translation for CEnergyCyclingDialog.cpp from qtlinguist. I couldn't find a difference here, this may be related to commit 4668488c?
1. Open the track to route conversion dialog.
2. Dialog should be in german language.
3. Move mouse over the various track to route icons.
4. Tool-Tip should be in german language.
=> Update german translation

changelog.txt, src/qmapshack/CMainWindow.cpp
QMS-#421
Added the missing line
* Rename map view
* POI tab must change name
=> [QMS-421]  Change of map view name is not taken into account in POI tab

changelog.txt, src/qmapshack/dem/CDemPathSetup.cpp, src/qmapshack/gis/rte/router/routino/CRouterRoutinoPathSetup.cpp, src/qmapshack/map/CMapPathSetup.cpp, src/qmapshack/poi/CPoiPathSetup.cpp
QMS-#427
The last argument of getExistingDirectory function is a flag and cannot
be zero according to Qt documentation. I think the default value
QFileDialog::ShowDirsOnly should work. It fixes the issue for me.
1. Click RMB in the maps panel and select "Setup map paths"
2. Press the "plus" button.
3. Select any directory and press OK.
4. A directory is now added to the list of map paths.
=> [QMS-427] Adding new map paths is broken 

changelog.txt, src/qmapshack/gis/prj/CDetailsPrj.cpp
QMS-[439](https://github.com/Maproom/qmapshack/issues/439)
Add count of tracks prior to the string "Tracks" in headerline for tracks list in project edit dialog.
1. Open some projects
2. Verify that the number of tracks is correct
=> [QMS-439] Add number of tracks in a project in headline in detail project track list

changelog.txt, src/qmapshack/CMainWindow.cpp, src/qmapshack/CMainWindow.h
QMS-#436
* Store name in file
* Restore name from file
* Additionally use view name for cloned view with suffix
1. Give your view a name
2. Store view to file
3. Close view
4. Restore view from file
--> The view's name should be restored.
=> [QMS-436] Store/restore name of map view

changelog.txt, src/qmapshack/locale/qmapshack_es.ts
QMS-#444
Edit `qmapshack_es.ts` to fix the wrong link
Assuming you are using qmapshack in spanish
1. Go to ' POI list panel' 
2. If any path to POI folders is configured you will see a help message with a link: ' Configurar rutas a los POI' 
3. Click on the link and the POI folders path configuration dialogue opens.
- [x ] yes
- [ x] yes
- [ x] yes, I didn't forget to change changelog.txt
=> [QMS-444] Fix wrong link to POI path setup in Spanish translation file

changelog.txt, src/qmapshack/dem/CDemVRT.cpp, src/qmapshack/map/CMapTMS.cpp, src/qmapshack/map/CMapVRT.cpp, src/qmapshack/map/CMapWMTS.cpp, src/qmaptool/canvas/CDrawContextPixel.cpp, src/qmaptool/helpers/CGdalFile.cpp, src/qmt_map2jnx/main.cpp
QMS-#438
Replace 'exportToProj4' by 'exportToWkt' in CDemVRT.cpp and CMapVRT.cpp. This preserves the "towgs84" datum shift needed by some SRSs
For reference: 
There is a warning about the use of `exportToProj`function in GDAL documentation, 
[here](https://gdal.org/api/ogrspatialref.html#_CPPv4NK19OGRSpatialReference13exportToProj4EPPc) and [here](https://gdal.org/api/ogr_srs_api.html#_CPPv416OSRExportToProj420OGRSpatialReferenceHPPc)
1. Download [this zip](https://mega.nz/file/BFdDFSbA#0VR7Vb7G2-V65ZzTP03mMrr3LFZwmnheO5YTXxd1p-w). It is only 135 Kb and contains a sample DEM for testing and a gpx file with a waypoint to land on the sample DEM area (Klosterwappen in Austria) …
=> [QMS-438] Replace 'exportToProj4' by 'exportToWkt' 

changelog.txt, src/qmapshack/dem/CDemPropSetup.cpp, src/qmapshack/dem/CDemPropSetup.h, src/qmapshack/dem/CDemVRT.cpp, src/qmapshack/dem/CDemVRT.h, src/qmapshack/dem/IDem.cpp, src/qmapshack/dem/IDem.h, src/qmapshack/dem/IDemList.ui, src/qmapshack/dem/IDemPropSetup.ui
Added functionality in the DEM to color the map by the elevation
values including a switchable coresponding color scale legend and
min/max elevation spinners in the DEM property dialog.
Modified the scroll setting in the DEM list to allow for proper
scrolling of the DEM property tree widget.
QMS-#476
[comment]: (Describe roughly.)
I've implemented the code that enables to color the map by elevation. Everything was implemented within the DEM folder.
Changed the scroll policy in the DEM list / property setup widget for a proper scrolling to enable that all widgets can be 
accessed properly. 
1. Open DEM Properties
2. Enable Elevation Shading check box and change elevation limits / toggle legend.
=> [QM-476] Color the map by elevation

changelog.txt, src/qmapshack/dem/CDemPropSetup.cpp, src/qmapshack/dem/CDemVRT.cpp, src/qmapshack/dem/IDem.cpp, src/qmapshack/dem/IDem.h, src/qmapshack/dem/IDemPropSetup.ui
QMS-#483
Added alpha transparency based slope shading layer where slope angle is mapped to transpareny.
Slope angle is evaluated using already implemented algorithm.
Layer at slope angle 0 degrees is fully transparent, layer at slope angle 90 degrees is fully opaque.
Slider may reduce slope angle down to 30 degrees where layer is fully opaque.
1. Open window Dig. Elev. Model (DEM)
2. Open VRT entry
3. Check _Slope Shading_ checkbutton
4. Position corresponding slider at the left side
Scaling factor is now 0.25 and slope relief 's opacity is at it's minimum.
5. Move corresponding slider to the right side
Slope relief becomes more and more stronger and slopes are becoming more …
=> [QMS-483] Add alpha transparency based hillshading

changelog.txt, src/qmapshack/dem/IDemPropSetup.ui
QMS-#487
Add tooltips for DEM controls
1. Go to DEM panel and activate some DEM
2. Open DEM properties and hover the cursor over each control to see the tooltips.
=> [QMS-487] Add tooltips for DEM controls

changelog.txt, src/qmapshack/dem/IDem.cpp
QMS-#490
Calculation of the slope value can result in value NOFLOAT depending on DEM data. Case was unhandled before.
Expanded slope shading opacity calculation by mapping slope value NOFLOAT to alpha value 0 i.e. fully transparent.
1. Enable slope shading
2. Move map window's position to boundary of available DEM data.
3. Slope shading layer without DEM data should be fully transparent.
4. Slope calculation exactly on boundary of DEM data may be impossible due to missing elevation data outside of boundary. Therefore slope shading layer on boundary of DEM data should be fully transparent
=> [QMS-490] Potentially incorrect slope shading opacity for slope value NOFLOAT

changelog.txt, src/qmapshack/mouse/range/CScrOptRangeTool.cpp
QMS-#489
Use the internal API to decrement the selection. 
Perform steps from ticket
=> [QMS-489] Track selection 0-index bug

changelog.txt, src/qmapshack/gis/CGisListWks.cpp
Those projects can't be closed.
QMS-#499
Simply set the enable state according to the autom. sync to device state.
1. Open several projects
2. Set one to "autom. sync. w. device"
3. Right click on project: "Close" disabled
4. Right click on other project: "Close" enabled
5. Group select projects: "Close" is enabled/disabled according to the first selected project
=> [QMS-499] Disable Close action for projects with autom. sync. to device

changelog.txt, src/qmapshack/poi/CRawPoi.cpp
QMS-#429
- fix the bug described in the issue
- implement warning for other unexpected cases
1. Edit poi file so that a poi data column contains a line with no `=` sign. Make sure the line breaks are CR (hex: 0d)
2. Activate the poi file and the according category and center on the poi
3. see that QMS no longer crashes.
=> [QMS-429] Bad OSM Tag formatting crashes QMS

changelog.txt, src/qmaptool/overlay/refmap/CProjWizard.cpp
Check for empty string and stop bfore the the bla bla starts
QMS-#507
Check for empty projection  string and abort validity check  before the the bla bla starts
Use instructions from ticket
=> [QMS-507] QMapTool: Early projection validity check

changelog.txt, src/qmapshack/gis/rte/router/brouter/CRouterBRouterLocal.cpp, src/qmapshack/gis/rte/router/brouter/CRouterBRouterSetup.cpp, src/qmapshack/gis/rte/router/brouter/CRouterBRouterSetup.h, src/qmapshack/gis/rte/router/brouter/CRouterBRouterSetupWizard.cpp, src/qmapshack/gis/rte/router/brouter/CRouterBRouterSetupWizard.h, src/qmapshack/gis/rte/router/brouter/IRouterBRouterSetupWizard.ui
QMS-#503
adjusted the local brouter-setup wizard to work with the new zip-file format of brouter-version >=1.6.3
Open BRouter->Setup->local installation->update existing BRouter installation->brouter-1.6.3.zip->Download and install->(wait for installation to finish->next ...
=> [QMS-503] fix brouter local setup

changelog.txt, src/qmapshack/map/WorldSat.wmts, src/qmapshack/map/WorldTopo.wmts
QMS-#522
Fixed the built-in wmts files of WorldTopo and WorldSat
* Activate one of the maps
* Check if map is loading and displayed
=> [QMS-522] Change URLs of built-in maps from http to https

changelog.txt, src/qmapshack/gis/IGisWorkspace.ui, src/qmapshack/gis/summary/CGisSummaryDropZone.cpp
QMS-#537
Set the drag-n-drop mode of the workspace from internal move to real drag-n-drop. By that the copy action can be selected.
Copy won't remove the origin items
See ticket for instructions
=> [QMS-537] Moving items to drop zone removes them from workspace

CMakeLists.txt, changelog.txt, src/qmapshack/CMakeLists.txt, src/qmapshack/gis/wpt/CDetailsGeoCache.cpp, src/qmapshack/gis/wpt/CDetailsWpt.cpp, src/qmapshack/gis/wpt/CGisItemWpt.cpp, src/qmapshack/gis/wpt/CGisItemWpt.h, src/qmapshack/helpers/CTimeDialog.cpp, src/qmapshack/helpers/CTimeDialog.h, src/qmapshack/helpers/ITimeDialog.ui, src/qmapshack/widgets/CDateTimeEditor.cpp, src/qmapshack/widgets/CDateTimeEditor.h, uncrustify.cfg
QMS-#518
Added a new dialog to edit the timestamps of waypoints, 
* Create waypoint
* Click on the linked timestamp
* Edit timestamp
=> QMS-518 Editable Timestamps for waypoints

changelog.txt, src/qmapshack/map/CMapPropSetup.cpp
QMS-#535
The check boxes where not updated in ` CMapPropSetup::slotPropertiesChanged()` 
See ticket for instructions
=> [QMS-535] Loading a map view does not reset the layer checkboxes

changelog.txt, src/qmapshack/gis/CGisListWks.cpp
QMS-#542
Switch mode between DragDrop and internal move
See ticket
=> [QMS-542] Changed drag`n drop in workspace

changelog.txt, src/qmapshack/gis/fit/serialization.cpp, src/qmapshack/gis/prj/CDetailsPrj.cpp, src/qmapshack/gis/prj/IGisProject.cpp, src/qmapshack/gis/rte/CGisItemRte.cpp, src/qmapshack/gis/trk/CGisItemTrk.cpp, src/qmapshack/gis/trk/CListTrkPts.cpp, src/qmapshack/gis/trk/CTableTrk.cpp, src/qmapshack/gis/wpt/CDetailsWpt.cpp, src/qmapshack/gis/wpt/CGisItemWpt.cpp, src/qmapshack/units/IUnit.cpp, src/qmapshack/units/IUnit.h
QMS-551
Set QDateTime short format back to Qt::ISODate in IUnit::datetime2string for qmapshack and qmaptool.
Note:
QDateTime is overloaded and can take two arguments:
enum Qt::DateFormat for Qt::ISODate
and
const QString for QLocale().dateTimeFormat(QLocale::LongFormat)
1. Connect Garmin device with fit format ==> ISODate will be used as track (file) name.
2. Set in View / Setup Time zone long format, Exit QMS and restart
Edit a track ==> in track info long format will be shown
=> [QMS-551] Set QDateTime short format back to Qt::ISODate

changelog.txt, src/qmapshack/gis/trk/filter/filter.cpp
QMS-#560
I fixed the filter function filterSplitTrack to include all points of the original track and not generate empty tracks or tracks with just one point. In addition tracks points are distributed more equally over the track "segments".
1. Open a track
2. Right-click on the track, Edit, Filter, Miscellaneous
3. Split track into multiple shorter tracks: Select number of tracks to split into and press apply button.
4. Confirm dialog and check if new tracks are generated and contain the correct track points
=> [QMS-560] Fix FilterSplitTrack

changelog.txt, src/qmapshack/gis/rte/router/brouter/CRouterBRouterSetup.cpp
QMS-#594
changed the regular expression that parses the result of executing 'java -version' (resp. 'java --version') to detect version s that consist of a major version only (with no minor-version separated by '.' being defined).
1. Open brouter setup wizard, choose 'local installation', do not check 'expert-mode'
2. click next to the dialog that allows to choose the java executable
3. click 'search for installed java'
4. verify that no warning 'Your Java version unknown seems to be older than the required version xxx' is being displayed.
=> [QMS-594] adjust java version parsing regex to allow pure major version schemes

changelog.txt, src/qmapshack/dem/CDemVRT.cpp, src/qmapshack/dem/IDem.cpp, src/qmapshack/dem/IDem.h
QMS-#606
Read data from files as float instead of uin16. Process data as float.
Use Lidar data for DEM layer. Old version will show shading as stair cases. This patch will do a smooth shading.
=> [QMS-606] Better hillshading with high resolution Lidar data

changelog.txt, src/qmapshack/canvas/IDrawContext.cpp, src/qmapshack/canvas/IDrawContext.h, src/qmapshack/canvas/IDrawObject.cpp, src/qmapshack/canvas/IDrawObject.h, src/qmapshack/dem/CDemVRT.cpp, src/qmapshack/dem/CDemVRT.h, src/qmapshack/dem/IDem.cpp, src/qmapshack/dem/IDem.h
QMS-#612
Move tile rendering into it's own method and call this method from a thread pool.
* Load DEM Data
* Enable hillshading or any other overlay feature
* Test performance and stability
=> [QMS-612] Optimize DEM rendering by using a thread pool

changelog.txt, src/qmapshack/main.cpp, src/qmapshack/setup/IAppSetup.cpp, src/qmapshack/setup/IAppSetup.h
QMS-#615
Add includes for OS specific classes
Compile for Windows
=> [QMS-615] Syntax error when compiling QMS for Windows

changelog.txt, src/qmapshack/CMakeLists.txt, src/qmapshack/gis/rte/router/CRouterBRouter.cpp, src/qmapshack/gis/rte/router/brouter/CRouterBRouterDownloadPage.cpp, src/qmapshack/gis/rte/router/brouter/CRouterBRouterDownloadPage.h, src/qmapshack/gis/rte/router/brouter/CRouterBRouterLocal.cpp, src/qmapshack/gis/rte/router/brouter/CRouterBRouterSetup.cpp, src/qmapshack/gis/rte/router/brouter/CRouterBRouterSetup.h, src/qmapshack/gis/rte/router/brouter/CRouterBRouterSetupPage.cpp, src/qmapshack/gis/rte/router/brouter/CRouterBRouterSetupPage.h, src/qmapshack/gis/rte/router/brouter/CRouterBRouterSetupWizard.cpp, src/qmapshack/gis/rte/router/brouter/CRouterBRouterSetupWizard.h, src/qmapshack/gis/rte/router/brouter/CRouterBRouterToolShell.cpp, src/qmapshack/gis/rte/router/brouter/IRouterBRouterSetupWizard.ui, src/qmapshack/tool/IToolShell.h
QMS-#622
the url that is used to download brouter binaries from has been changed to brouter releases page on github
1. Open brouter setup-wizzard
2. choose 'local installation'
3. click 'update existing BRouter installation'
4. click 'v1.7.2'
5. click 'Download and Install'
6. the log-output should end with 'installation successful'
=> [QMS-622] change installation-source of brouter to github

changelog.txt, src/qmapshack/gis/rte/router/CRouterBRouter.cpp
[comment]: #
QMS-#630
[comment]: # enabled processing of userInterfaceEvents in local brouter synchronous request processing to allow cancellation of progress-dialog.
[comment]: #
1. in router config dialog choose BRouter (offline)
2. if not yet done install BRouter locally klicking Setup and make sure to successfully complete the brouter installation wizzard downloading some tiles that cover a lager area.
3. zoom the map to a location that is covered by brouter routing data (see tiles download dialog in install wizzard).
4. right click on the map, choose a point that is located on some street or path that is likely to be inclused in brouter routing data.
5. zoom out and move to a location that of both some 100km away from the starting-point and also covered by brouter routing data.
6. …
=> [QMS-630] on-the-fly routing cannot be canceled

changelog.txt, src/qmapshack/gis/rte/router/brouter/CRouterBRouterToolShell.cpp, src/qmapshack/gis/rte/router/brouter/CRouterBRouterToolShell.h
QMS-#623
to distinguish normal shutdown from errors during startup a timer was used. Any transition to processState::NotRunning that would happen after expiry of this timer would not result in showing the error but would be ignored silently.
The timer has been replaced by a boolean flag 'isBeingStopped' that is set to false on process startup and to true when klicking the stop-button.
1. make sure BRouter is installed locally.
2. validate local BRouter starts fine by clicking the start/stop-button to the right of 'BRouter: stopped'
3. validate 'BRouter: stopped' has changed to 'BRouter: running' and that a second button did appear to the right of the start-button.
4. stop local BRouter by clicking the start/stop-button. Now 'BRouter: stopped' should be displayed again.
5. while QMapShack …
=> [QMS-623] remove use of QTimer in brouter startup error detection

changelog.txt, src/qmapshack/map/CMapTMS.cpp, src/qmapshack/map/CMapWMTS.cpp
QMS-#656
More recent Qt5 versions send the QListWidget::itemChanged() signal also on QListWidgetItem::setData(). This will reset the layer's enable flag.  The trick is to cache the flag on the stack and apply the flag as the last step.
Use the Google TMS file and enable the 1st layer only. Reload the map. Without the fix the layer is not displayed after reload. With the fix the layer is displayed properly.
=> [QMS-656] TMS/WMTS: Fix loosing layer selection when reloading maps

changelog.txt, src/qmapshack/map/CMapIMG.cpp, src/qmapshack/map/CMapIMG.h, src/qmapshack/map/garmin/CGarminTyp.cpp
QMS-#675
Simply use the information form the typ file to draw the lables
Use a Garmin map with typ file, that defines colored lables. e.g.Freizeitkarte
=> [QMS-675] The label colors defined in the TYP are not used

changelog.txt, src/qmapshack/gis/trk/CGisItemTrk.cpp, src/qmapshack/gis/trk/CGisItemTrk.h
QMS-#683
Replace deprecated API by new API call
See ticket
=> [QMS-683] Fix alglib error on interpolation

changelog.txt, src/qmapshack/gis/trk/CGisItemTrk.cpp
QMS-#692
To get a better mean of the values metadata for a point is calculated by selecting the points +- 25 m form that point. Only if a point far enough is found the variables to derive all secondary data are set. For some points in the middle no other point has a distance of 25m. Therefor both points are the same resulting in an invalid slope.
Solution: If no point is 25m away use the one that is most far.
Use the track from the ticket
=> [QMS-692] Trackpoints erroneously flaged invalid for short tracks (<50m)

src/qmapshack/gis/rte/router/CRouterBRouter.cpp, src/qmapshack/gis/rte/router/brouter/CRouterBRouterSetup.cpp, src/qmapshack/helpers/CTimeDialog.cpp, src/qmapshack/map/CMapRMAP.cpp
QMS-#697
Search for QByteArray and use QByteArray::data() whenever a string conversion is done.
There is no real bad case except in loading RMap.  But there is a list of functions that should be tested as good as possible:
* all time zone related stuff
* RMap support 
* BRouter setup and support
* Realtime data all modules.
=> [QMS-697]  Fix QByteArray to QString decoding

changelog.txt, src/qmapshack/units/IUnit.cpp
QMS-#699
Replaced `QSetting cfg;` with `SETTINGS;` and included `CSettings.h` in `IUnit.cpp`
1. Start QMS with command line parameter `-c ~/qms.conf`
2. The default config file will not be overwritten
This change needs also to be included in the porting_qt6 branch
=> [QMS-699]  Fix writing to default config when using commandline parameter -c

changelog.txt, src/qmapshack/helpers/CWptIconManager.cpp
QMS-706
Extract PNG offset by QImage::offset() function from user-defined waypoint icon file.
For offset value = (0,0) use icon center as offset (and preserve compatibility!),
for offset value ≠ (0,0) use this offset value.
Store offset value in "wptIcons".
1. Add a PNG file with offset value ≠ (0,0) as user-defined waypoint icon to "External Icons" folder,
e.g. [png_with_offset](https://github.com/user-attachments/assets/5e9afe04-7952-4590-a632-886aa76ee738).
2. Create a waypoint on map using this waypoint icon
3. Verify that pin's tip is at waypoint position and does not obscur waypoint.
4. Add a PNG file without offset or with offset value = (0,0) as user-defined waypoint …
=> Apply PNG file’s offset to user-defined waypoint icon from "External Icons" folder

changelog.txt, src/qmapshack/canvas/IDrawContext.cpp, src/qmapshack/grid/CProjWizard.cpp, src/qmaptool/overlay/refmap/CProjWizard.cpp
QMS-#709
A- Adjust square zoom levels to fit EPSG:3857 tiles according to proposed changes in #709
B- Minor fix in Proj Wizard UI to get World Mercator (OSM) button checked  if EPSG:3857 was previously selected.
1. Open Setup Map View, choose Square for Scales
2. Hit upper right grid button in same window and choose `World Mercator (OSM)` as projection
3. Choose OSM Topo as map
4. Search location Frankfurt, Germany, de
5. Zoom map to scale 100 m
6. Map looks sharp, not blurry.
1. Open Setup Map View, type `EPSG:3857` for Projection&Datum 
2. Hit upper right grid button in same window to open Proj Wizard
3. `World Mercator (OSM)` option appears checked
=> [QMS-709] Adjust square zoom levels to fit EPSG:3857 tiles and other minor fix

changelog.txt, src/qmapshack/map/IMapOnline.cpp
QMS-#715
- To prevent unnecessary tile map server requests and reduce server load as well as network traffic:
Add a tile request for a given URL to queue of pending requests only, if request for same tile is not already queued.
Remove all further queued requests for same URL.
Thus, server requests are reduced signifantly.  
- To follow HTTP(S) redirections:
Add policy to allow "http"->"http", "http" -> "https" or "https" -> "https" redirections.
In order to recognize reply belonging to request, use originally requested url due to possible redirects.
Test 1 - removing duplicate tile requests:
1. Open a tile map server map
2. Verify that despite of removing duplicates no tiles …
=> Remove duplicate tile map server requests for the same tile, allow HTTP(S) redirection

src/qmapshack/gis/prj/CDetailsPrj.cpp
QMS-https://github.com/Maproom/qmapshack/issues/648#issuecomment-2634284430
Added `setBorderCollapse(false);` which defaults to true in new QT versions.
1. with 1.17.1 the table borders of the diary are shown
2. with porting-qt6 the table borders of the diary are missing
=> Make table borders visible again

CMakeLists.txt, changelog.txt
QMS-#648
Added a version check for Qt as some changes require recent version
Try to cmake with a version less than 6.8.0 and with a version larger than 6.8.0
=> Add Qt version check

cmake/Modules/DefineInstallationPaths.cmake
In order to allow distributors to change file locations, i.e. for documentation, remove the FORCE value so locations can changed as neeed.
QMS-#
1. Open whatever
2. Click here
=> cmake: allow variable customization

changelog.txt, src/qmapshack/map/CMapTMS.cpp, src/qmapshack/map/CMapWMTS.cpp
QMS-#730
Re-added namespace processing for xml files. The namespace processing was accidentally removed by fixing deprecation warnings.
1. Activate a WMTS or TMS map
2. An errorwindow is displayed
=> readd namespace processing

CMakeLists.txt, MacOSX/build-QMS.sh, MacOSX/build-all.sh, MacOSX/build-gdal.sh, MacOSX/build-proj.sh, MacOSX/build-quazip.sh, MacOSX/build-routino.sh, MacOSX/bundle-all.sh, MacOSX/bundle-common-func.sh, MacOSX/bundle-qmapshack.sh, MacOSX/bundle-qmaptool.sh, MacOSX/config.sh, MacOSX/install-packages.sh, changelog.txt
QMS-#732
- Update dependency versions:
- Proj to 9.6.0 (from 9.3.0)
- Routino to 3.4.2 (from 3.4.1)
- GDAL to 3.10
- Proj data to 1.21 (from 1.15)
- Adapt CMake configuration and build scripts (build-*.sh) for Qt6
- Update bundling scripts (bundle-*.sh) to handle Qt6
- Improve GDAL build configuration:
- Explicitly disable Python bindings
- Ensure local PROJ is used via PKG_CONFIG_PATH and CMAKE_PREFIX_PATH
- Fix GEOS usage flag
- Patch Routino Makefile for macOS compatibility (dynamiclib, rpath)
- Build PROJ from source by default (BUILD_PROJ="x").
- Refactor and clean up build and bundling scripts
- Use make -j$(sysctl -n hw.ncpu) for parallel builds
1. follow instructions …
=> [QMS-732]: build scripts for macOS don't support qt6

changelog.txt, src/qmapshack/CMakeLists.txt, src/qmapshack/gis/prj/IGisProject.cpp
QMS-#740
Move all DBus dependent code for MTP devices into the USE_QT6DBus sections of the CMakeLists files
Try to compile in Windows.
=> [QMS-740] Fix dbus compile issues for Windows

changelog.txt, src/qmapshack/gis/rte/router/brouter/CRouterBRouterSetup.cpp, src/qmapshack/gis/rte/router/brouter/CRouterBRouterSetupWizard.cpp
QMS-#664
- make error message about unknown java version less confusing
- make finding a too old java version a non-fatal error
- make java version check more accepting
1. Open BRouter setup wizard
2. Click through it
the series is properly atomized - don't squash-merge.
=> broute java setup related fixes

changelog.txt, src/qmapshack/plot/IPlot.cpp
QMS-#743
Make sure the smart pointer is not null
See ticket
=> [QMS-743] Fix crash when reseting a range in track profile graph

3rdparty/GarminFitSdk/CMakeLists.txt, changelog.txt, src/qmapshack/CMakeLists.txt
QMS-#750
Make the compile switches UNIX dependent
Should compile for Windows and Linux
=> [QMS-750] Fix QMS build error - Windows 10/MSVC

changelog.txt, src/qmapshack/gis/rte/router/brouter/CRouterBRouterSetup.cpp
QMS-756
Check if value of variable `localJavaExecutable` is an empty string `""`.
If yes, prevent from starting executable set by variable `localJavaExecutable`
to avoid Qt warnings `[warning] QIODevice::read (QProcess): device not open`
1. Run `<QMS installation folder>/QMapShack.exe -c <empty configuration file>` on Windows OS from command line
2. See **no** Qt warnings `[warning] QIODevice::read (QProcess): device not open` in output console
=> [QMS-756] Avoid: [warning] QIODevice::read (QProcess): device not open

changelog.txt, src/qmapshack/CMainWindow.h
QMS-#757
If procedure `homeDir.path()` returns an empty string `""`
prevent from calling procedure `homeDir.exists(...)`
to avoid Qt warnings `[warning] Empty filename passed to function`.
1. Run `<QMS installation folder>/QMapShack.exe -c <empty configuration file>` from command line
2. See **no** Qt warnings `[warning] Empty filename passed to function in output console`
Notes on OS Windows:
Running executable from `cmd.exe` console prevents from seeing any stdout and stderr output.
Running executable however from Cygwin, MingGW, MSYS, ... console, or running from Windows powershell using
command line `& <QMS installation folder>/QMapShack.exe -c <empty configuration file> …
=> [QMS-757] Avoid: [warning] Empty filename passed to function

changelog.txt, src/qmapshack/gis/CGisListWks.cpp
QMS-#758
To avoid Qt warnings `[warning] QSqlError("19", "Unable to fetch row", "NOT NULL constraint failed: workspace.name")`
or `[warning] QSqlError("1299", "Unable to fetch row", "NOT NULL constraint failed: workspace.name")`,
prevent from updating SQL table `workspace` if table item `name` with constraint `NOT NULL` is an empty string `""`
which is considered by SQL to be `NULL`.
1. Run `<QMS installation folder>/QMapShack.exe` from command line
2. Wait for automatic save and/or quit QMS
3. See **no** Qt warnings
`[warning] Execution of SQL-Statement "INSERT INTO workspace (type, keyqms, name, changed, visible, data) VALUES (:type, :keyqms, :name, :changed, :visible, …
=> [QMS-758] Avoid: [warning] QSqlError("19", "Unable to fetch row", "NOT NULL constraint failed: workspace.name")

changelog.txt, src/qmapshack/canvas/CCanvas.cpp
QMS-#759
Prevent from calculating and setting height of QTextBrowser widget `textStatusMessage` within invisible view(s)
to avoid Qt warnings
`[warning] QWidget::setMinimumSize: (/QTextBrowser) Negative sizes (300,-140) are not possible`
and
`[warning] QWidget::setMaximumSize: (/QTextBrowser) Negative sizes (16777215,-140) are not possible`.
Height of invisible view(s) may be wrong and different from height of map drawing area.
Therefore calculation of `textStatusMessage` widget's height within invisible view may be wrong and even negative .
1. Run `<QMS installation folder>/QMapShack.exe` from command line
2. Define at least 2 views
3. Quit QMS
4. Run `<QMS installation …
=> [QMS-759] Avoid: [warning] QWidget::setMinimumSize: (/QTextBrowser) Negative sizes (300,-140) are not possible

changelog.txt, src/qmapshack/CMainWindow.cpp
QMS-#766
Prevent Qt from throwing warning message
`[warning] QMainWindow::addDockWidget: invalid 'area' argument`
when calling local help by keyboard key F1.
1. Run QMS
2. Hit keyboard key F1
3. See no Qt warning `[warning] QMainWindow::addDockWidget: invalid 'area' argument` in ouput console
=> [QMS-766] [warning] QMainWindow::addDockWidget

changelog.txt, src/qmapshack/gis/rte/router/brouter/CRouterBRouterTilesPage.cpp
QMS-#777
Encapsulated 3 dialog texts by `tr()` macro
in order to be able to assign translations using `QT Linguist`.
1. Verify that text strings of source file `CRouterBRouterTilesPage.cpp` are encapsulated by `tr()` macro
=> [QMS-777] BRouter segments download "Cancel" dialog

changelog.txt, src/qmapshack/gis/fit2/CFit2Project.cpp, src/qmapshack/gis/fit2/CFit2Project.h
[QMS-771](https://github.com/Maproom/qmapshack/issues/771)
- Restructured code based on different methods for chronological messages ordering
- Removed createTrack method
- Built trackname when a courses message is available otherwise built trackname from first trackpoint
- Adapted event handling for the different devices to create new segments
- Added timerTime value to show in trackpoint comment
- Removed extension distance
- Adapted handling of extension EnhanceSpeed for track comment
- Changed extension enhanceRespirationRate from float to int
- Beautified the code
- Read Fit files from different devices
- Check consistency of track in QMS
=> [QMS-771] Adapt Fit2 Implementation

changelog.txt, src/qmapshack/gis/trk/CTableTrk.cpp, src/qmapshack/units/IUnit.cpp, src/qmapshack/units/IUnit.h
[QMS-782](https://github.com/Maproom/qmapshack/issues/782)
- Show time with seconds
- Show value for slope, ascent, descent with "-" when trackpoint elevation is invalid
1. Load a track with invalid elevation at the beginning of the track
2. Do not delete the invalid tracks
3. Edit track, show track point editor
=> [QMS-782] Solved two issues for track point viewer

changelog.txt, src/qmapshack/gis/rte/router/CRouterSetup.h
QMS-#788
Removed MapQuest router from enumeration. The enumeration is used to index the combobox items when changing the text.
see ticket
=> [QMS-788] Fix: BRouter (offline) not shown in combobox

changelog.txt, src/qmapshack/gis/rte/router/brouter/CRouterBRouterSetup.cpp
QMS-#791
Fixed QRegularExpression to extract BRouter version from BRouter reply.
1. Setup routing and select BRouter-Web (online) as router
2. No error message window is showing BRouter related errors
=> [QMS-791] Error determining BRouter-Web (online) version

changelog.txt, src/qmapshack/gis/ovl/IScrOptOvlArea.ui, src/qmapshack/gis/rte/IScrOptRte.ui, src/qmapshack/gis/trk/IScrOptTrk.ui, src/qmapshack/gis/wpt/IScrOptWpt.ui
QMS-#794
- Edit ` IScrOptWpt.ui ` with Qt Designer, and set the property `openExternalLink` to true for `TextLabel`
- Do the same fix for`IScrOptTrk.ui`, `IScrOptRte.ui`and `IScrOptOvlArea.ui`
1. Edit a waypoint and create a link pointing to  a local file.(e.g.   file.jpg  file.pdf) 
2. Click this waypoint on the map - click on the link to the local file - file is opened
=> [QMS-794]Fix: Links to local files not opening in Waypoint on-screen dialog

changelog.txt, src/qmapshack/gis/rte/router/CRouterBRouter.cpp, src/qmapshack/gis/rte/router/CRouterSetup.cpp, src/qmapshack/gis/rte/router/CRouterSetup.h, src/qmapshack/gis/rte/router/IRouterBRouter.ui, src/qmapshack/gis/rte/router/brouter/CRouterBRouterLocal.cpp, src/qmapshack/gis/rte/router/brouter/CRouterBRouterSetupWizard.cpp, src/qmapshack/mouse/line/IMouseEditLine.cpp, src/qmapshack/mouse/line/IMouseEditLine.h, src/qmapshack/mouse/line/IScrOptEditLine.ui
QMS-#793
- Remove BRouter's obsolete "on-the-fly routing" checkbox: 
auto-routing is now always usable with _offline_ routers and is never usable with _online_ router
- Replace checkbox by a hint in case of auto-routing not available with BRouter
- Disable/enable "A" button depending on router's auto-routing capability: 
-  at begin of editing line 
- while editing line by signaling new router's auto-routing capability after router switch
- Fix incorrect BRouter-Web version shown in BRouter setup window
- Fix alternate index count in tooltip of calculated route: was 1 to high
index 0 = original, index n = n-th alternative
- Fix line edit "A" button tooltip's incomplete phrase …
=> [QMS-793] Auto-routing with BRouter & minor fixes

changelog.txt, src/qmapshack/CMakeLists.txt, src/qmapshack/device/CDeviceAccessGvfsMtp.cpp, src/qmapshack/device/CDeviceAccessGvfsMtp.h, src/qmapshack/device/CDeviceAccessKMtp.cpp, src/qmapshack/device/CDeviceAccessKMtp.h, src/qmapshack/device/CDeviceGarminMtp.cpp, src/qmapshack/device/CDeviceGenericMtp.cpp, src/qmapshack/device/CDeviceGenericMtp.h, src/qmapshack/device/CDeviceWatcherLinux.cpp, src/qmapshack/device/CDeviceWatcherLinux.h, src/qmapshack/device/IDevice.h, src/qmapshack/device/IDeviceAccess.h, src/qmapshack/gis/IGisItem.cpp, src/qmapshack/gis/gpx/serialization.cpp, src/qmapshack/gis/prj/IGisProject.cpp
[QMS-797](https://github.com/Maproom/qmapshack/issues/797)
Establish an integration for USB MTP generic devices (Wahho, Hammerhead, mobile phones, etc.) similar to the already existing integration for GARMIN USB MTP devices.
Tested on:
Linux Fedora Workstation 41, GNOME/Wayland for gvfs support
Linux Fedora Workstation 42, KDE/Wayland for kiod6 support
You need a USB MTP devices
1. Create a JSON file `QmsMtpDevice.json` in the top level storage directory
2. Adapt the JSON file according to your GPS file directory structure
3. Create the GPS file directory structure
4. Optional: Copy an icon to the QMS data directory structure and reference the path in the JSON file  
5. Start QMS
==> You should see the generic device in the workspace tree
6. Perform your actions: Copy, Delete, Sync, ...
=> [QMS-797] Enhance USB MTP to support generic devices

changelog.txt, src/qmapshack/canvas/CCanvas.cpp, src/qmapshack/gis/rte/router/brouter/CRouterBRouterTilesSelectArea.cpp
QMS-#811
Fixed 2 fatal tooltip errors occuring with wayland platform
while hovering over
1. POI icons - file `CCanvas.cpp`
2. BRouter offline tile areas - file `CRouterBRouterTilesSelectArea.cpp`
Error 1:
Follow steps **To Reproduce** of issue #811 and notice any more neither of problems described there.
Error 2:
1. Follow steps to **Setup BRouter local installation/offline** until BRouter tile selection window is shown
2. Hover over tiles and notice tooltips popping up
This was and still is working as expected. 
3. Select at least one tile to download
4. Hit "Cancel" button
5. In confirmation dialog window hit "Continue with Setup" button
6. Hover over tiles and notice …
=> [QMS-811] Fix 2 fatal tooltip errors with wayland platform

changelog.txt, src/qmapshack/IAbout.ui, src/qmapshack/gis/prj/CDetailsPrj.cpp
QMS-#826
Somehow referencing items of a list/vector by a pointer while appending the list/vector is a bad idea. Therefore create a temporary pointer on-the-fly if the list is large enough
See ticket
=> [QMS-826] Fix: "to next" values missing in project diary

changelog.txt, src/qmapshack/plot/IPlot.cpp
QMS-#834
Added statement `USE_ANTI_ALIASING(p, true);`
to file `src/qmapshack/plot/IPlot.cpp` procedure `IPlot::paintEvent`
1. Set environment variable QT_SCALE_FACTOR to a value different from 1.0, e.g. to value 1.25
2. Run QMS within environment
3. Notice entire QMS application's main window is smoothly scaled
4. Create track with waypoints
5. Show track's profile in toplevel window
6. **Notice line edges, icons and text in track's profile window are now smoothly scaled too**
=> [QMS-834] Non-antialiased scaled track profile
